module DeployAssist
  module ConfigGenerators
    class CredentialsYmlGenerator
      def initialize(deployment_setup, service_configuration)
        @setup = deployment_setup
        @config = service_configuration
        @results = service_configuration.automation_results
      end

      def generate
        <<~YAML
          # Generated by DeployAssist
          # Run: EDITOR="code --wait" rails credentials:edit --environment production

          secret_key_base: #{SecureRandom.hex(64)}

          aws:
            access_key_id: #{iam_access_key}
            secret_access_key: #{iam_secret_key}
            region: #{aws_region}
            s3_bucket: #{s3_bucket_name}

          # Add your service credentials below
          # google:
          #   client_id: YOUR_GOOGLE_CLIENT_ID
          #   client_secret: YOUR_GOOGLE_CLIENT_SECRET
          #
          # stripe:
          #   publishable_key: YOUR_STRIPE_PUBLISHABLE_KEY
          #   secret_key: YOUR_STRIPE_SECRET_KEY
          #   webhook_secret: YOUR_STRIPE_WEBHOOK_SECRET
        YAML
      end

      private

      def iam_access_key
        @results.dig('iam_user', 'access_key_id') || 'YOUR_AWS_ACCESS_KEY_ID'
      end

      def iam_secret_key
        @results.dig('iam_user', 'secret_access_key') || 'YOUR_AWS_SECRET_ACCESS_KEY'
      end

      def aws_region
        @config.collected_data['region'] || DeployAssist.default_region
      end

      def s3_bucket_name
        @results.dig('s3_bucket', 'bucket_name') || "#{@setup.app_name}-production-storage"
      end
    end
  end
end
