module DeployAssist
  module ConfigGenerators
    class DatabaseYmlGenerator
      def initialize(deployment_setup, service_configuration)
        @setup = deployment_setup
        @config = service_configuration
        @data = service_configuration.collected_data
        @results = service_configuration.automation_results
      end

      def generate
        <<~YAML
          # Generated by DeployAssist
          # Database configuration for #{@setup.app_display_name}

          default: &default
            adapter: postgresql
            encoding: unicode
            pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

          development:
            <<: *default
            database: #{@setup.app_name}_development

          test:
            <<: *default
            database: #{@setup.app_name}_test

          production:
            primary:
              <<: *default
              database: postgres
              username: #{db_username}
              password: <%= ENV["#{@setup.app_name.upcase}_DATABASE_PASSWORD"] %>
              host: <%= ENV.fetch("DB_HOST") { "#{rds_endpoint}" } %>
              port: 5432

            cache:
              <<: *default
              database: #{@setup.app_name}_production_cache
              username: #{db_username}
              password: <%= ENV["#{@setup.app_name.upcase}_DATABASE_PASSWORD"] %>
              host: <%= ENV.fetch("DB_HOST") { "#{rds_endpoint}" } %>
              migrations_paths: db/cache_migrate

            queue:
              <<: *default
              database: #{@setup.app_name}_production_queue
              username: #{db_username}
              password: <%= ENV["#{@setup.app_name.upcase}_DATABASE_PASSWORD"] %>
              host: <%= ENV.fetch("DB_HOST") { "#{rds_endpoint}" } %>
              migrations_paths: db/queue_migrate

            cable:
              <<: *default
              database: #{@setup.app_name}_production_cable
              username: #{db_username}
              password: <%= ENV["#{@setup.app_name.upcase}_DATABASE_PASSWORD"] %>
              host: <%= ENV.fetch("DB_HOST") { "#{rds_endpoint}" } %>
              migrations_paths: db/cable_migrate
        YAML
      end

      private

      def db_username
        @results.dig('rds_database', 'master_username') || 'postgres'
      end

      def rds_endpoint
        @results.dig('rds_database', 'endpoint') || 'your-rds-endpoint.us-east-1.rds.amazonaws.com'
      end
    end
  end
end
