module DeployAssist
  module ConfigGenerators
    class KamalConfigGenerator
      def initialize(deployment_setup, service_configuration)
        @setup = deployment_setup
        @config = service_configuration
        @data = service_configuration.collected_data
        @results = service_configuration.automation_results
      end

      def generate
        <<~YAML
          # Generated by DeployAssist for: #{@setup.app_display_name}
          # Environment: #{@setup.environment}
          # Generated at: #{Time.current.strftime('%Y-%m-%d %H:%M:%S')}

          service: #{@setup.app_name}
          image: #{docker_username}/#{@setup.app_name}

          servers:
            web:
              - EC2_PUBLIC_IP_HERE  # Add your EC2 instance IP

          registry:
            username: #{docker_username}
            password:
              - KAMAL_REGISTRY_PASSWORD

          env:
            secret:
              - RAILS_MASTER_KEY
              - #{@setup.app_name.upcase}_DATABASE_PASSWORD
            clear:
              DB_HOST: #{rds_endpoint}
              AWS_REGION: #{aws_region}
              AWS_S3_BUCKET: #{s3_bucket_name}
              SOLID_QUEUE_IN_PUMA: true

          volumes:
            - "#{@setup.app_name}_storage:/rails/storage"

          ssh:
            user: ec2-user
            keys:
              - ~/.ssh/#{@setup.app_name}-key.pem

          proxy:
            ssl: true
            host: #{@setup.domain || 'yourapp.com'}
            healthcheck:
              path: /up

          asset_path: /rails/public/assets

          builder:
            arch: amd64
        YAML
      end

      private

      def docker_username
        @data['docker_username'] || 'your-docker-username'
      end

      def rds_endpoint
        if @results.dig('rds_database', 'endpoint')
          @results.dig('rds_database', 'endpoint')
        elsif @results.dig('rds_database', 'db_instance_identifier')
          "#{@results['rds_database']['db_instance_identifier']}.REGION.rds.amazonaws.com"
        else
          'your-rds-endpoint.us-east-1.rds.amazonaws.com'
        end
      end

      def aws_region
        @data['region'] || DeployAssist.default_region
      end

      def s3_bucket_name
        @results.dig('s3_bucket', 'bucket_name') || "#{@setup.app_name}-production-storage"
      end
    end
  end
end
